// Clue banks for Crossword. Answers are A–Z only, 3–9 letters (the grid is 11 wide),
// and no word appears in both banks (Mix uses them together).

export interface Entry {
  word: string
  clue: string
}

export const THEMES = ['ghana', 'games', 'mix'] as const
export type Theme = (typeof THEMES)[number]
export const THEME_LABEL: Record<Theme, string> = { ghana: 'Ghana', games: 'Games', mix: 'Mix' }

const GHANA: Entry[] = [
  // the country, places and nature
  { word: 'GHANA', clue: 'West African nation known for gold and kente' },
  { word: 'ACCRA', clue: 'Capital city on the Gulf of Guinea' },
  { word: 'KUMASI', clue: 'The Garden City, seat of the Asantehene' },
  { word: 'TEMA', clue: 'Port city east of Accra' },
  { word: 'TAMALE', clue: 'Capital of the Northern Region' },
  { word: 'ELMINA', clue: 'Coastal town with a 15th-century castle' },
  { word: 'CAPE', clue: '___ Coast, home of a famous castle' },
  { word: 'ADA', clue: 'Town where the Volta meets the sea' },
  { word: 'KOFORIDUA', clue: 'Capital of the Eastern Region' },
  { word: 'SUNYANI', clue: 'Capital of the Bono Region' },
  { word: 'TAKORADI', clue: 'Western Region port, twin city of Sekondi' },
  { word: 'SEKONDI', clue: 'Twin city of Takoradi' },
  { word: 'OBUASI', clue: 'Ashanti town famous for its gold mine' },
  { word: 'TARKWA', clue: 'Western Region gold-mining town' },
  { word: 'WINNEBA', clue: 'Coastal town of the Aboakyer festival' },
  { word: 'AFLAO', clue: 'Border town on the road to Lomé' },
  { word: 'KETA', clue: 'Volta Region town beside a big lagoon' },
  { word: 'AKOSOMBO', clue: 'Town of the great dam on the Volta' },
  { word: 'NKAWKAW', clue: 'Town at the foot of the Kwahu ridge' },
  { word: 'KWAHU', clue: 'Plateau famous for Easter paragliding' },
  { word: 'ABURI', clue: 'Hill town known for its botanical gardens' },
  { word: 'TESHIE', clue: 'Accra town famed for fantasy coffins' },
  { word: 'LABADI', clue: 'Popular beach in Accra' },
  { word: 'OSU', clue: 'Accra district of Oxford Street' },
  { word: 'MAKOLA', clue: 'Busy market in the heart of Accra' },
  { word: 'KANESHIE', clue: 'Accra market and neighbourhood' },
  { word: 'LEGON', clue: 'Home of the University of Ghana' },
  { word: 'KASOA', clue: 'Fast-growing town on the Accra–Cape Coast road' },
  { word: 'PAGA', clue: 'Northern town of the sacred crocodile ponds' },
  { word: 'LARABANGA', clue: 'Village with a centuries-old mud mosque' },
  { word: 'MOLE', clue: '___ National Park, where elephants roam' },
  { word: 'KAKUM', clue: 'Park famous for its canopy walkway' },
  { word: 'BUSUA', clue: 'Western beach village popular with surfers' },
  { word: 'AXIM', clue: 'Western coastal town with Fort St Anthony' },
  { word: 'KINTAMPO', clue: 'Bono East town known for its waterfalls' },
  { word: 'NSAWAM', clue: 'Eastern Region town known for pineapples' },
  { word: 'AKUAPEM', clue: 'Ridge north of Accra, home of the Odwira' },
  { word: 'BOLGA', clue: 'Short name for the Upper East capital' },
  { word: 'NIMA', clue: 'Busy zongo neighbourhood of Accra' },
  { word: 'JAMESTOWN', clue: 'Old Accra district with a lighthouse' },
  { word: 'SHAI', clue: '___ Hills, wildlife reserve near Dodowa' },
  { word: 'BUKOM', clue: 'Accra neighbourhood that breeds boxers' },
  { word: 'VOLTA', clue: 'Great river dammed at Akosombo' },
  { word: 'LAKE', clue: 'Volta ___, one of the world’s largest reservoirs' },
  { word: 'PRA', clue: 'River that reaches the sea near Shama' },
  { word: 'ANKOBRA', clue: 'Western river with gold along its banks' },
  { word: 'DENSU', clue: 'River dammed at Weija to supply Accra' },
  { word: 'BIRIM', clue: 'Eastern river known for diamonds' },
  { word: 'OTI', clue: 'River, and the region named after it' },
  { word: 'TANO', clue: 'River that rises near Techiman and runs to the Ivorian border' },
  { word: 'BOSUMTWI', clue: 'Crater lake near Kumasi' },
  { word: 'AFADJATO', clue: 'Ghana’s highest mountain' },
  { word: 'WLI', clue: '___ Falls, Volta Region waterfall' },
  { word: 'SAVANNAH', clue: 'Region and grassland of the north' },
  { word: 'AHAFO', clue: 'Region whose capital is Goaso' },
  { word: 'BONO', clue: 'Region whose capital is Sunyani' },
  { word: 'NORTHERN', clue: 'Region whose capital is Tamale' },
  { word: 'LAGOON', clue: 'Keta has a big one' },
  { word: 'HARMATTAN', clue: 'Dusty dry wind of December and January' },
  { word: 'BAOBAB', clue: 'Fat-trunked tree of the northern savannah' },
  { word: 'ODUM', clue: 'Twi name for the iroko tree' },
  { word: 'MAHOGANY', clue: 'Prized reddish hardwood of the forest' },
  { word: 'TEAK', clue: 'Hardwood timber tree' },
  { word: 'PALM', clue: 'Tree that gives cooking oil and wine' },
  { word: 'MONKEY', clue: 'Resident of the Tafi Atome sanctuary' },
  { word: 'AKRANTIE', clue: 'Grasscutter, a prized bushmeat' },
  // people, languages and history
  { word: 'AKAN', clue: 'Largest ethnic group in Ghana' },
  { word: 'EWE', clue: 'People of the Volta Region' },
  { word: 'ASANTE', clue: 'Kingdom of the Golden Stool' },
  { word: 'ASHANTI', clue: 'Region whose capital is Kumasi' },
  { word: 'FANTE', clue: 'Akan people of the Central coast' },
  { word: 'TWI', clue: 'Most widely spoken Akan language' },
  { word: 'DAGBANI', clue: 'Main language of Tamale' },
  { word: 'DAGOMBA', clue: 'People of the kingdom of Dagbon' },
  { word: 'NZEMA', clue: 'People of the far south-west coast' },
  { word: 'GONJA', clue: 'Northern kingdom founded by Ndewura Jakpa' },
  { word: 'FRAFRA', clue: 'Upper East people known for straw baskets' },
  { word: 'KROBO', clue: 'People of Somanya and Odumase' },
  { word: 'DANGME', clue: 'Language of Ada and the Krobo' },
  { word: 'ANLO', clue: 'Ewe people of the Keta coast' },
  { word: 'HAUSA', clue: 'Language heard in every zongo' },
  { word: 'NKRUMAH', clue: 'First president: Kwame ___' },
  { word: 'DANQUAH', clue: 'J. B. ___, one of the Big Six' },
  { word: 'BUSIA', clue: 'Prime minister of the Second Republic' },
  { word: 'RAWLINGS', clue: 'Flight lieutenant who led Ghana for two decades' },
  { word: 'KUFUOR', clue: 'President from 2001 to 2009' },
  { word: 'MAHAMA', clue: 'President John Dramani ___' },
  { word: 'ANNAN', clue: 'Kofi ___, UN Secretary-General' },
  { word: 'OSEI', clue: '___ Tutu, founder of the Asante kingdom' },
  { word: 'ANOKYE', clue: 'Okomfo ___, priest who called down the Golden Stool' },
  { word: 'ASANTEWAA', clue: 'Yaa ___, queen mother who led the 1900 war' },
  { word: 'PREMPEH', clue: 'Asante king exiled to the Seychelles' },
  { word: 'GOLD', clue: '___ Coast, the colonial name' },
  { word: 'MARCH', clue: 'Independence Day is the 6th of this month' },
  { word: 'JUBILEE', clue: 'Golden ___ House, seat of government' },
  { word: 'FLAGSTAFF', clue: '___ House, the old presidential residence' },
  { word: 'STAR', clue: 'Black emblem at the centre of the flag' },
  { word: 'EAGLE', clue: 'Golden bird on the coat of arms' },
  { word: 'SQUARE', clue: 'Black Star ___, Accra’s parade ground' },
  { word: 'CASTLE', clue: 'Cape Coast ___, on the coast since the 1600s' },
  { word: 'CPP', clue: 'Nkrumah’s party, by its initials' },
  // food and drink
  { word: 'FUFU', clue: 'Pounded cassava and plantain, eaten with soup' },
  { word: 'JOLLOF', clue: 'Spicy rice dish of a famous friendly rivalry' },
  { word: 'KENKEY', clue: 'Fermented corn dough, wrapped in husks' },
  { word: 'BANKU', clue: 'Corn and cassava dough, great with tilapia' },
  { word: 'WAAKYE', clue: 'Rice and beans, a favourite breakfast' },
  { word: 'SHITO', clue: 'Hot black pepper sauce' },
  { word: 'KELEWELE', clue: 'Spicy fried plantain cubes' },
  { word: 'GARI', clue: 'Dry cassava granules, soaked or with beans' },
  { word: 'KOKO', clue: 'Millet porridge sold at dawn' },
  { word: 'KOOSE', clue: 'Bean fritters, often eaten with koko' },
  { word: 'BOFROT', clue: 'Sweet fried dough ball' },
  { word: 'AMPESI', clue: 'Boiled yam or plantain, with stew' },
  { word: 'ETO', clue: 'Mashed yam with palm oil and eggs' },
  { word: 'AKPLE', clue: 'Ewe corn dough, served with okro soup' },
  { word: 'ABENKWAN', clue: 'Palm nut soup' },
  { word: 'NKATEKWAN', clue: 'Groundnut soup' },
  { word: 'KONTOMIRE', clue: 'Cocoyam leaves, cooked into stew' },
  { word: 'SOBOLO', clue: 'Chilled hibiscus drink' },
  { word: 'PITO', clue: 'Millet beer of the north' },
  { word: 'TILAPIA', clue: 'Fish grilled whole and served with banku' },
  { word: 'PLANTAIN', clue: 'Starchy cousin of the banana' },
  { word: 'CASSAVA', clue: 'Root crop behind gari and fufu' },
  { word: 'GROUNDNUT', clue: 'Peanut, as Ghanaians call it' },
  { word: 'OKRO', clue: 'Slimy green vegetable for soup' },
  { word: 'YAM', clue: 'Tuber celebrated at harvest festivals' },
  { word: 'CHOFI', clue: 'Fried turkey tail' },
  { word: 'CHICHINGA', clue: 'Spicy meat on a stick' },
  { word: 'KOOBI', clue: 'Salted dried tilapia' },
  { word: 'MOMONE', clue: 'Pungent fermented fish for seasoning' },
  { word: 'DAWADAWA', clue: 'Fermented locust bean seasoning' },
  { word: 'TATALE', clue: 'Pancake of overripe plantain' },
  { word: 'SHEA', clue: '___ butter, pressed from nuts in the north' },
  { word: 'COCOA', clue: 'Key cash crop of the forest belt' },
  { word: 'COCOBOD', clue: 'Board that buys the cocoa crop' },
  { word: 'CASHEW', clue: 'Nut grown widely in the Bono Region' },
  { word: 'KOLA', clue: '___ nut, offered as a traditional gift' },
  // culture, festivals and daily life
  { word: 'KENTE', clue: 'Colourful handwoven royal cloth' },
  { word: 'ADINKRA', clue: 'Printed symbols, each with a meaning' },
  { word: 'SANKOFA', clue: 'Adinkra bird looking back: learn from the past' },
  { word: 'GYENYAME', clue: 'Adinkra symbol meaning “except God”' },
  { word: 'STOOL', clue: 'The Golden ___, Asante symbol of power' },
  { word: 'DRUM', clue: 'Talking ___, used to send messages' },
  { word: 'OKYEAME', clue: 'The chief’s spokesman' },
  { word: 'DURBAR', clue: 'Grand gathering of chiefs at a festival' },
  { word: 'SMOCK', clue: 'Striped northern garment worn by chiefs' },
  { word: 'FUGU', clue: 'Smock, in the north' },
  { word: 'BEADS', clue: 'What the Krobo are famous for making' },
  { word: 'CALABASH', clue: 'Dried gourd used as a bowl' },
  { word: 'HOMOWO', clue: 'Ga harvest festival that “hoots at hunger”' },
  { word: 'ODWIRA', clue: 'Akuapem festival of cleansing' },
  { word: 'AKWASIDAE', clue: 'Asante festival held every six weeks' },
  { word: 'ABOAKYER', clue: 'Winneba festival of the deer hunt' },
  { word: 'DAMBA', clue: 'Northern festival marking the Prophet’s birth' },
  { word: 'FETU', clue: '___ Afahye, Cape Coast’s festival' },
  { word: 'ANANSE', clue: 'Kwaku ___, the trickster spider' },
  { word: 'HIGHLIFE', clue: 'Guitar-and-horns music born in Ghana' },
  { word: 'HIPLIFE', clue: 'Highlife meets hip hop' },
  { word: 'AZONTO', clue: 'Dance craze of the early 2010s' },
  { word: 'SARKODIE', clue: 'Tema rapper who raps in Twi' },
  { word: 'AMPE', clue: 'Jump-and-clap game played by girls' },
  { word: 'OWARE', clue: 'Seed-sowing board game played across Ghana' },
  { word: 'TROTRO', clue: 'Shared minibus that gets everyone around' },
  { word: 'OKADA', clue: 'Motorbike taxi' },
  { word: 'DUMSOR', clue: 'Lights off, lights on: power cuts' },
  { word: 'CHALE', clue: 'Slang for “my friend”' },
  { word: 'AKWAABA', clue: 'Welcome!' },
  { word: 'MEDAASE', clue: 'Thank you, in Twi' },
  { word: 'OBRONI', clue: 'What children call a foreigner' },
  { word: 'WOFA', clue: 'Uncle, in Twi' },
  { word: 'CEDI', clue: 'Ghana’s currency' },
  { word: 'PESEWA', clue: 'One hundredth of a cedi' },
  { word: 'BAUXITE', clue: 'Aluminium ore mined at Awaso' },
  { word: 'MANGANESE', clue: 'Metal ore mined at Nsuta' },
  { word: 'OIL', clue: 'Found offshore in the Jubilee field' },
  { word: 'TIMBER', clue: 'Logs from the forest belt, a big export' },
  // football and sport
  { word: 'STARS', clue: 'Black ___, the national football team' },
  { word: 'HEARTS', clue: 'Accra ___ of Oak' },
  { word: 'KOTOKO', clue: 'Asante ___, the Porcupine Warriors' },
  { word: 'ABEDI', clue: '___ Pelé, three-time African Footballer of the Year' },
  { word: 'ESSIEN', clue: 'Michael ___, Chelsea midfield powerhouse' },
  { word: 'GYAN', clue: 'Asamoah ___, record goalscorer' },
  { word: 'AYEW', clue: 'Family name of Abedi’s footballing sons' },
  { word: 'AZUMAH', clue: '___ Nelson, boxing world champion' },
  // Akan day names
  { word: 'KWASI', clue: 'Akan name for a boy born on Sunday' },
  { word: 'AKOSUA', clue: 'Akan name for a girl born on Sunday' },
  { word: 'KWADWO', clue: 'Akan name for a boy born on Monday' },
  { word: 'ADWOA', clue: 'Akan name for a girl born on Monday' },
  { word: 'KWABENA', clue: 'Akan name for a boy born on Tuesday' },
  { word: 'ABENA', clue: 'Akan name for a girl born on Tuesday' },
  { word: 'KWAKU', clue: 'Akan name for a boy born on Wednesday' },
  { word: 'AKUA', clue: 'Akan name for a girl born on Wednesday' },
  { word: 'YAW', clue: 'Akan name for a boy born on Thursday' },
  { word: 'YAA', clue: 'Akan name for a girl born on Thursday' },
  { word: 'KOFI', clue: 'Akan name for a boy born on Friday' },
  { word: 'AFUA', clue: 'Akan name for a girl born on Friday' },
  { word: 'KWAME', clue: 'Akan name for a boy born on Saturday' },
  { word: 'AMA', clue: 'Akan name for a girl born on Saturday' },
  { word: 'ESI', clue: 'Fante name for a girl born on Sunday' },
  { word: 'EKOW', clue: 'Fante name for a boy born on Thursday' },
]

const GAMES: Entry[] = [
  // board games
  { word: 'LUDO', clue: 'Roll a six to bring a token out' },
  { word: 'TOKEN', clue: 'Coloured piece raced around a Ludo board' },
  { word: 'HOME', clue: 'Where Ludo tokens finish' },
  { word: 'SIX', clue: 'The roll that gets you out of the yard' },
  { word: 'DICE', clue: 'Six-sided cubes of chance' },
  { word: 'ROLL', clue: 'Send the dice spinning' },
  { word: 'DOUBLES', clue: 'Both dice the same' },
  { word: 'BOARD', clue: 'Flat surface for tabletop games' },
  { word: 'PIECE', clue: 'Anything you move around a board' },
  { word: 'COUNTER', clue: 'Small disc moved round a board' },
  { word: 'SPINNER', clue: 'Arrow you flick instead of rolling dice' },
  { word: 'SNAKES', clue: '___ and ladders' },
  { word: 'LADDERS', clue: 'They take you up; the snakes take you down' },
  { word: 'MONOPOLY', clue: 'Buy streets, build hotels, bankrupt your friends' },
  { word: 'SCRABBLE', clue: 'Word game of lettered tiles and triple scores' },
  { word: 'TILE', clue: 'Lettered piece in Scrabble' },
  { word: 'CLUEDO', clue: 'Whodunnit: in the library, with the rope' },
  { word: 'RISK', clue: 'Board game of world domination' },
  { word: 'JENGA', clue: 'Pull a block out, don’t topple the tower' },
  { word: 'MANCALA', clue: 'Family of seed-sowing games' },
  { word: 'SEED', clue: 'What gets sown in Oware' },
  { word: 'START', clue: 'Square where every token begins' },
  { word: 'FINISH', clue: 'End of the race' },
  { word: 'REVERSI', clue: 'Othello by another name' },
  { word: 'FLIP', clue: 'Turn a disc to your colour' },
  { word: 'DISC', clue: 'Round piece dropped in Connect Four' },
  { word: 'NOUGHTS', clue: '___ and crosses' },
  { word: 'CROSSES', clue: 'Noughts and ___' },
  { word: 'BOX', clue: 'Close one in Dots & Boxes and go again' },
  { word: 'FLEET', clue: 'Your five ships in Battleship' },
  { word: 'SALVO', clue: 'Several shots fired at once' },
  { word: 'HIT', clue: 'Battleship shot that finds a ship' },
  { word: 'MISS', clue: 'Battleship shot that finds only water' },
  { word: 'SINK', clue: 'Hit every square of a ship' },
  { word: 'DOMINO', clue: 'Spotted tile, matched end to end' },
  { word: 'DRAUGHTS', clue: 'Another name for checkers' },
  { word: 'JUMP', clue: 'How a checker captures' },
  { word: 'CROWN', clue: 'A checker earns one on the far row' },
  // chess
  { word: 'CHESS', clue: 'Strategy game of kings and queens' },
  { word: 'KING', clue: 'Crowned piece in chess or checkers' },
  { word: 'QUEEN', clue: 'Most powerful chess piece' },
  { word: 'ROOK', clue: 'Castle-shaped chess piece' },
  { word: 'BISHOP', clue: 'Chess piece that moves diagonally' },
  { word: 'KNIGHT', clue: 'Chess piece that jumps in an L' },
  { word: 'PAWN', clue: 'Smallest chess piece' },
  { word: 'CHECK', clue: 'Warning that the king is under attack' },
  { word: 'MATE', clue: 'Friend, or the end of a chess game' },
  { word: 'CHECKMATE', clue: 'King trapped: game over' },
  { word: 'STALEMATE', clue: 'Chess draw with no legal move' },
  { word: 'GAMBIT', clue: 'Opening that gives up a pawn for position' },
  { word: 'ENPASSANT', clue: 'Pawn capture “in passing”' },
  { word: 'PROMOTE', clue: 'Turn a pawn into a queen' },
  { word: 'FORK', clue: 'One piece attacking two at once' },
  { word: 'PIN', clue: 'A piece that can’t move without exposing another' },
  { word: 'SKEWER', clue: 'Attack through one piece to the one behind' },
  { word: 'BLITZ', clue: 'Chess at lightning speed' },
  { word: 'OPENING', clue: 'The first moves of a game' },
  { word: 'ENDGAME', clue: 'The last stage, with few pieces left' },
  { word: 'RESIGN', clue: 'Give up before mate' },
  { word: 'ELO', clue: 'Rating system for chess players' },
  { word: 'RANK', clue: 'A row on a chessboard' },
  { word: 'FILE', clue: 'A column on a chessboard' },
  { word: 'CAPTURE', clue: 'Take an opponent’s piece' },
  // cards
  { word: 'CARD', clue: 'One of fifty-two in a deck' },
  { word: 'DECK', clue: 'All fifty-two cards' },
  { word: 'SUIT', clue: 'Hearts, clubs, diamonds or spades' },
  { word: 'SPADES', clue: 'Suit shaped like an upside-down heart on a stalk' },
  { word: 'CLUBS', clue: 'Suit of black trefoils' },
  { word: 'DIAMONDS', clue: 'Red suit of lozenges' },
  { word: 'ACE', clue: 'Card that can be high or low' },
  { word: 'KNAVE', clue: 'Old name for the jack' },
  { word: 'JACK', clue: 'Card between ten and queen' },
  { word: 'JOKER', clue: 'Wild card in a deck' },
  { word: 'WILD', clue: '___ card, stands for anything' },
  { word: 'TRUMP', clue: 'Suit that beats all the others' },
  { word: 'TRICK', clue: 'One card from each player, taken by the best' },
  { word: 'HAND', clue: 'The cards you hold' },
  { word: 'DEAL', clue: 'Hand out the cards' },
  { word: 'SHUFFLE', clue: 'Mix the deck' },
  { word: 'CUT', clue: 'Split the deck before dealing' },
  { word: 'DISCARD', clue: 'Throw away a card' },
  { word: 'SNAP', clue: 'Shout it when two cards match' },
  { word: 'RUMMY', clue: 'Card game of sets and runs' },
  { word: 'SOLITAIRE', clue: 'Card game for one' },
  { word: 'PATIENCE', clue: 'Another name for solitaire' },
  { word: 'BRIDGE', clue: 'Card game of bids and partners' },
  { word: 'UNO', clue: 'Shout it with one card left' },
  { word: 'WHOT', clue: 'Card game with stars, circles and crosses' },
  { word: 'SPAR', clue: 'Card game where only the last trick counts' },
  { word: 'POKER', clue: 'Card game of chips and bluffs' },
  { word: 'BLUFF', clue: 'Pretend your hand is better than it is' },
  { word: 'ANTE', clue: 'Stake paid before the deal' },
  { word: 'FOLD', clue: 'Give up the hand' },
  { word: 'RAISE', clue: 'Bet more than the last player' },
  { word: 'CHIPS', clue: 'Plastic discs used as stakes' },
  { word: 'FLUSH', clue: 'Five cards of one suit' },
  { word: 'POT', clue: 'All the chips in the middle' },
  { word: 'JACKPOT', clue: 'The big prize' },
  // chance
  { word: 'LUCK', clue: 'What dice players pray for' },
  { word: 'CHANCE', clue: 'Monopoly card pile, or luck itself' },
  { word: 'ODDS', clue: 'How likely it is' },
  { word: 'COIN', clue: 'Tossed to decide who starts' },
  { word: 'TOSS', clue: 'Flip a coin' },
  { word: 'HEADS', clue: 'One side of a coin' },
  { word: 'TAILS', clue: 'The other side of the coin' },
  // word and puzzle games
  { word: 'HANGMAN', clue: 'Guess the word before he swings' },
  { word: 'ANAGRAM', clue: 'Rearrange the letters' },
  { word: 'CROSSWORD', clue: 'You’re playing one' },
  { word: 'BOGGLE', clue: 'Shake the letter cubes, find words' },
  { word: 'WORDLE', clue: 'Five letters, six tries, green and yellow' },
  { word: 'PUN', clue: 'A play on words' },
  { word: 'SPELL', clue: 'Put the letters in order' },
  { word: 'VOWEL', clue: 'A, E, I, O or U' },
  { word: 'LETTER', clue: 'One of twenty-six' },
  { word: 'CLUE', clue: 'Hint that leads to an answer' },
  { word: 'HINT', clue: 'A little help' },
  { word: 'ANSWER', clue: 'What the clue leads to' },
  { word: 'SOLVE', clue: 'Crack the puzzle' },
  { word: 'GRID', clue: 'Rows and columns of squares' },
  { word: 'SUDOKU', clue: 'Number puzzle on a 9×9 grid' },
  { word: 'KAKURO', clue: 'Number crossword of sums' },
  { word: 'JIGSAW', clue: 'Puzzle of interlocking pieces' },
  { word: 'RUBIK', clue: '___’s Cube' },
  { word: 'TANGRAM', clue: 'Seven shapes, make a picture' },
  { word: 'LOGIC', clue: 'Reasoning a puzzle out' },
  { word: 'MAZE', clue: 'Find your way through it' },
  { word: 'LABYRINTH', clue: 'A maze, grandly' },
  { word: 'CIPHER', clue: 'Secret code to crack' },
  { word: 'RIDDLE', clue: 'Question with a clever answer' },
  { word: 'PUZZLE', clue: 'Brain-teaser to be solved' },
  { word: 'QUIZ', clue: 'Test of what you know' },
  { word: 'TRIVIA', clue: 'Little facts for a quiz' },
  { word: 'BRAIN', clue: 'What a teaser teases' },
  // party and playground
  { word: 'TAG', clue: 'You’re it!' },
  { word: 'SEEK', clue: 'Hide and ___' },
  { word: 'DARE', clue: 'Truth or ___' },
  { word: 'CHARADES', clue: 'Act it out, no talking' },
  { word: 'TWISTER', clue: 'Left hand on red' },
  { word: 'MARBLES', clue: 'Glass balls flicked in a ring' },
  { word: 'HOPSCOTCH', clue: 'Hop through chalk squares' },
  { word: 'SKIPPING', clue: 'Jumping over a turning rope' },
  { word: 'TUG', clue: '___ of war' },
  { word: 'RELAY', clue: 'Race where you pass the baton' },
  { word: 'BINGO', clue: 'Shout it when your card is full' },
  // video games
  { word: 'PIXEL', clue: 'One dot of a screen' },
  { word: 'ARCADE', clue: 'Hall of coin-operated games' },
  { word: 'CONSOLE', clue: 'PlayStation or Xbox' },
  { word: 'JOYSTICK', clue: 'Stick you steer with' },
  { word: 'PACMAN', clue: 'Yellow dot-eater chased by ghosts' },
  { word: 'MARIO', clue: 'Nintendo plumber' },
  { word: 'TETRIS', clue: 'Falling blocks, clear the lines' },
  { word: 'ZELDA', clue: 'The Legend of ___' },
  { word: 'SONIC', clue: 'Speedy blue hedgehog' },
  { word: 'FIFA', clue: 'Football game, or football’s governing body' },
  { word: 'BOSS', clue: 'Big enemy at the end of a level' },
  { word: 'LIVES', clue: 'Lose them all and it’s game over' },
  { word: 'SPAWN', clue: 'Appear in the game' },
  { word: 'RESPAWN', clue: 'Come back after being knocked out' },
  { word: 'QUEST', clue: 'Mission in an adventure game' },
  { word: 'AVATAR', clue: 'Your character on screen' },
  { word: 'GAMER', clue: 'One who plays video games' },
  { word: 'NOOB', clue: 'Beginner, in gamer slang' },
  { word: 'LAG', clue: 'Delay that ruins online play' },
  { word: 'SAVE', clue: 'Keep your progress' },
  { word: 'LEVEL', clue: 'Stage of a video game' },
  { word: 'BONUS', clue: 'Extra points' },
  // competing
  { word: 'GAME', clue: 'Something to play' },
  { word: 'PLAY', clue: 'Take part in a game' },
  { word: 'MOVE', clue: 'Your go in a board game' },
  { word: 'TURN', clue: 'Whose ___ is it?' },
  { word: 'PASS', clue: 'Skip your go' },
  { word: 'RULE', clue: 'What every player must follow' },
  { word: 'MATCH', clue: 'A contest between two' },
  { word: 'ROUND', clue: 'One part of a match' },
  { word: 'SERIES', clue: 'Best of five, say' },
  { word: 'REMATCH', clue: 'Another go after losing' },
  { word: 'REPLAY', clue: 'Play it again' },
  { word: 'UNDO', clue: 'Take back a move' },
  { word: 'WIN', clue: 'Come out on top' },
  { word: 'DRAW', clue: 'Neither player wins' },
  { word: 'TIE', clue: 'Level at the end' },
  { word: 'TIEBREAK', clue: 'Decider when it’s level' },
  { word: 'VICTORY', clue: 'A win' },
  { word: 'DEFEAT', clue: 'A loss' },
  { word: 'LOSER', clue: 'The one who didn’t win' },
  { word: 'CHAMPION', clue: 'Best of them all' },
  { word: 'RIVAL', clue: 'The one you most want to beat' },
  { word: 'OPPONENT', clue: 'The player across the table' },
  { word: 'SCORE', clue: 'Tally of points' },
  { word: 'POINT', clue: 'One unit of score' },
  { word: 'LEAD', clue: 'Be ahead' },
  { word: 'STREAK', clue: 'Several wins in a row' },
  { word: 'TROPHY', clue: 'Cup for the winner' },
  { word: 'MEDAL', clue: 'Gold, silver or bronze' },
  { word: 'PODIUM', clue: 'Where the top three stand' },
  { word: 'LEAGUE', clue: 'Teams that play each other all season' },
  { word: 'CUP', clue: 'Knockout competition' },
  { word: 'FINAL', clue: 'The last match' },
  { word: 'SEMI', clue: 'Match before the final, for short' },
  { word: 'REFEREE', clue: 'Football’s man in the middle' },
  { word: 'UMPIRE', clue: 'Tennis or cricket official' },
  { word: 'FOUL', clue: 'Break the rules' },
  { word: 'CHEAT', clue: 'Win unfairly' },
  { word: 'PENALTY', clue: 'Punishment for a foul' },
  { word: 'TEAM', clue: 'Players on the same side' },
  { word: 'PLAYER', clue: 'One taking part' },
  { word: 'STRATEGY', clue: 'Long-term game plan' },
  { word: 'TACTIC', clue: 'Short-term trick to gain an edge' },
  { word: 'TRAP', clue: 'Lure an opponent into a bad spot' },
  { word: 'ATTACK', clue: 'Go after the other side' },
  { word: 'DEFENCE', clue: 'Keeping them out' },
  { word: 'SACRIFICE', clue: 'Give up a piece on purpose' },
  { word: 'TIMER', clue: 'Counts down your turn' },
  { word: 'HOURGLASS', clue: 'Sand timer' },
]

export const BANKS: Record<Theme, Entry[]> = { ghana: GHANA, games: GAMES, mix: [...GHANA, ...GAMES] }
